-- ============================================================
-- supabase/init.sql
-- Standalone bootstrap for a fresh Supabase project.
-- Combines schema, security fixes, ambassador RPCs, and demo seed.
-- Does NOT include production PII / OAuth dumps.
--
-- Usage (SQL editor or psql Session mode, port 5432):
--   psql "postgres://postgres:<password>@db.<ref>.supabase.co:5432/postgres" \
--     -f supabase/init.sql
--
-- After running:
--   1. Enable Google OAuth in Supabase Auth
--   2. Copy .env.example → .env.local with project URL + anon key
--   3. First login creates a profile via /login/onboarding
--   4. To test teacher features: UPDATE profiles SET role = 'teacher' WHERE id = '<uuid>';
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- -------------------------------------------------------
-- Tables
-- -------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.appointments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_event_id text,
    user_id uuid,
    mentor_id uuid,
    status text,
    group_session_id bigint,
    user_priority_subject text,
    local_event_id text
);

COMMENT ON COLUMN public.appointments.user_priority_subject IS
  'Used to display a single subject when a session is applicable to multiple';
COMMENT ON COLUMN public.appointments.local_event_id IS
  'The ID of the user''s copy of the event';

CREATE TABLE IF NOT EXISTS public.events (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text,
    category text,
    date date,
    start_time time with time zone,
    end_time time with time zone,
    poster text,
    description text,
    contact_name text,
    contact_email text,
    sub_category text,
    year_groups numeric[],
    google_event_id text,
    invite_link text
);

COMMENT ON COLUMN public.events.sub_category IS 'One word with more information about the event';
COMMENT ON COLUMN public.events.year_groups IS 'applicable year groups';

CREATE TABLE IF NOT EXISTS public.group_mentoring_events (
    group_session_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    mentor_id uuid,
    title text,
    start_time time with time zone,
    end_time time with time zone,
    date date,
    description text,
    subjects text[],
    applicable_year_groups numeric[],
    location text,
    google_event_id text,
    invite_link text,
    "iCalUID" text
);

CREATE TABLE IF NOT EXISTS public.mentors (
    user_id uuid PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    description text,
    availability_text text,
    google_appointment_link text,
    email text,
    mentoring_subjects text[]
);

CREATE TABLE IF NOT EXISTS public.opportunities (
    opportunity_id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_updated timestamp with time zone DEFAULT now(),
    title text,
    full_description text,
    url text,
    submission_date date,
    contact_name text,
    contact_email text,
    opportunity_type text,
    internal boolean,
    online boolean,
    time_required numeric,
    advice text,
    weightage numeric,
    cost numeric DEFAULT 0,
    image text,
    one_off boolean,
    short_description text,
    year_groups numeric[],
    subjects text[],
    custom_opportunity boolean DEFAULT false,
    status text DEFAULT 'pending'::text,
    review_teacher text,
    submitted_by uuid,
    review_text text,
    past_projects text[]
);

COMMENT ON TABLE public.opportunities IS 'List of all supercurricular opportunities';
COMMENT ON COLUMN public.opportunities.time_required IS
  'Values correspond to (0-5): 0) A few hours 1) A few days 2) A couple of weeks 3) A month 4) A few months 5) More than a few months';
COMMENT ON COLUMN public.opportunities.short_description IS '1-2 short sentences';
COMMENT ON COLUMN public.opportunities.review_teacher IS
  'The email of the teacher responsible for approving the event';
COMMENT ON COLUMN public.opportunities.submitted_by IS 'ID of the person who submitted the activity';

CREATE TABLE IF NOT EXISTS public.portfolios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid,
    opportunity_id uuid,
    description text,
    project_files text[],
    status text,
    finished_at timestamp with time zone
);

-- profiles: OAuth tokens live in profile_tokens (not here)
CREATE TABLE IF NOT EXISTS public.profiles (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    first_name text,
    last_name text,
    id uuid PRIMARY KEY,
    current_year numeric,
    profile_url text,
    subjects text[],
    role text DEFAULT 'student'::text,
    email text,
    can_add boolean DEFAULT false,
    can_add_approver uuid
);

COMMENT ON COLUMN public.profiles.role IS 'student or teacher';
COMMENT ON COLUMN public.profiles.can_add_approver IS
  'Teacher who granted can_add (contributor / subject ambassador).';

-- Own-row Google OAuth tokens (Calendar integration)
CREATE TABLE IF NOT EXISTS public.profile_tokens (
    id uuid PRIMARY KEY,
    provider_token text,
    provider_refresh_token text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE public.profile_tokens IS
  'Google OAuth access/refresh tokens; own-row RLS only. Kept off profiles to avoid token leakage via authenticated SELECT.';

CREATE TABLE IF NOT EXISTS public.user_events (
    user_id uuid NOT NULL,
    event_id bigint NOT NULL,
    google_event_id text,
    PRIMARY KEY (user_id, event_id)
);

COMMENT ON TABLE public.user_events IS 'Events a user is attending';


-- -------------------------------------------------------
-- Foreign keys (idempotent)
-- mentors → profiles constraint name MUST be mentors_user_id_fkey1
-- (PostgREST embeds in lib/actions.ts use that hint)
-- -------------------------------------------------------

DO $$ BEGIN
  ALTER TABLE public.appointments
    ADD CONSTRAINT appointments_group_session_id_fkey
    FOREIGN KEY (group_session_id)
    REFERENCES public.group_mentoring_events(group_session_id)
    ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.appointments
    ADD CONSTRAINT appointments_mentor_id_fkey
    FOREIGN KEY (mentor_id)
    REFERENCES public.mentors(user_id)
    ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.appointments
    ADD CONSTRAINT appointments_user_id_fkey
    FOREIGN KEY (user_id)
    REFERENCES public.profiles(id)
    ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.group_mentoring_events
    ADD CONSTRAINT group_mentoring_events_mentor_id_fkey
    FOREIGN KEY (mentor_id)
    REFERENCES public.mentors(user_id)
    ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.group_mentoring_events
    ADD CONSTRAINT group_mentoring_events_mentor_profile_fkey
    FOREIGN KEY (mentor_id)
    REFERENCES public.profiles(id)
    ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.mentors
    ADD CONSTRAINT mentors_user_id_auth_fkey
    FOREIGN KEY (user_id)
    REFERENCES auth.users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.mentors
    ADD CONSTRAINT mentors_user_id_fkey1
    FOREIGN KEY (user_id)
    REFERENCES public.profiles(id)
    ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.opportunities
    ADD CONSTRAINT opportunities_submitted_by_fkey
    FOREIGN KEY (submitted_by)
    REFERENCES public.profiles(id)
    ON UPDATE CASCADE ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.portfolios
    ADD CONSTRAINT portfolios_opportunity_id_fkey
    FOREIGN KEY (opportunity_id)
    REFERENCES public.opportunities(opportunity_id)
    ON UPDATE CASCADE ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.portfolios
    ADD CONSTRAINT portfolios_user_id_fkey
    FOREIGN KEY (user_id)
    REFERENCES auth.users(id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.profiles
    ADD CONSTRAINT profiles_can_add_approver_fkey
    FOREIGN KEY (can_add_approver)
    REFERENCES public.profiles(id)
    ON UPDATE CASCADE ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.profiles
    ADD CONSTRAINT profiles_id_fkey
    FOREIGN KEY (id)
    REFERENCES auth.users(id)
    ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.profile_tokens
    ADD CONSTRAINT profile_tokens_id_fkey
    FOREIGN KEY (id)
    REFERENCES public.profiles(id)
    ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.user_events
    ADD CONSTRAINT user_events_event_id_fkey
    FOREIGN KEY (event_id)
    REFERENCES public.events(event_id)
    ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE public.user_events
    ADD CONSTRAINT user_events_user_id_fkey
    FOREIGN KEY (user_id)
    REFERENCES public.profiles(id)
    ON UPDATE CASCADE ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- -------------------------------------------------------
-- Privilege escalation guard (profiles)
-- Blocks authenticated clients from changing role / can_add /
-- can_add_approver. SECURITY DEFINER RPCs run as function owner
-- (postgres), so current_user is not 'authenticated' and they pass.
-- INSERT (onboarding) is allowed to set initial role.
-- -------------------------------------------------------

CREATE OR REPLACE FUNCTION public.prevent_privilege_escalation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'UPDATE'
     AND current_user IN ('authenticated', 'anon')
     AND (
       NEW.role IS DISTINCT FROM OLD.role
       OR NEW.can_add IS DISTINCT FROM OLD.can_add
       OR NEW.can_add_approver IS DISTINCT FROM OLD.can_add_approver
     ) THEN
    RAISE EXCEPTION 'Cannot modify privileged profile fields';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_prevent_privilege_escalation ON public.profiles;
CREATE TRIGGER trg_prevent_privilege_escalation
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE PROCEDURE public.prevent_privilege_escalation();

-- Keep profile_tokens.updated_at fresh
CREATE OR REPLACE FUNCTION public.touch_profile_tokens_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_profile_tokens_updated_at ON public.profile_tokens;
CREATE TRIGGER trg_touch_profile_tokens_updated_at
  BEFORE UPDATE ON public.profile_tokens
  FOR EACH ROW
  EXECUTE PROCEDURE public.touch_profile_tokens_updated_at();


-- -------------------------------------------------------
-- Ambassador RPCs (teachers grant/revoke can_add)
-- -------------------------------------------------------

CREATE OR REPLACE FUNCTION public.grant_can_add(target_student_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  caller_role text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT role INTO caller_role FROM public.profiles WHERE id = auth.uid();
  IF caller_role IS DISTINCT FROM 'teacher' THEN
    RAISE EXCEPTION 'Only teachers can grant contributor access';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = target_student_id AND role = 'student'
  ) THEN
    RAISE EXCEPTION 'Target must be a student profile';
  END IF;

  UPDATE public.profiles
  SET can_add = true,
      can_add_approver = auth.uid()
  WHERE id = target_student_id
    AND role = 'student';
END;
$$;

CREATE OR REPLACE FUNCTION public.revoke_can_add(target_student_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  caller_role text;
  rows_updated int;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  SELECT role INTO caller_role FROM public.profiles WHERE id = auth.uid();
  IF caller_role IS DISTINCT FROM 'teacher' THEN
    RAISE EXCEPTION 'Only teachers can revoke contributor access';
  END IF;

  UPDATE public.profiles
  SET can_add = false,
      can_add_approver = NULL
  WHERE id = target_student_id
    AND role = 'student'
    AND can_add_approver = auth.uid();

  GET DIAGNOSTICS rows_updated = ROW_COUNT;
  IF rows_updated = 0 THEN
    RAISE EXCEPTION 'No ambassador found that you approved, or already revoked';
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.grant_can_add(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.revoke_can_add(uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.grant_can_add(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_can_add(uuid) TO authenticated;


-- -------------------------------------------------------
-- Row Level Security
-- -------------------------------------------------------

ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_mentoring_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mentors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.opportunities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_events ENABLE ROW LEVEL SECURITY;

-- appointments
DROP POLICY IF EXISTS "Enable delete access for authenticated users" ON public.appointments;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.appointments;
DROP POLICY IF EXISTS "Enable read for authenticated users only" ON public.appointments;
CREATE POLICY "Enable delete access for authenticated users"
  ON public.appointments FOR DELETE TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only"
  ON public.appointments FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable read for authenticated users only"
  ON public.appointments FOR SELECT TO authenticated USING (true);

-- events (app inserts school events from authenticated clients)
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.events;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.events;
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON public.events;
DROP POLICY IF EXISTS "Enable delete for authenticated users only" ON public.events;
CREATE POLICY "Enable read access for authenticated users"
  ON public.events FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for authenticated users only"
  ON public.events FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable update for authenticated users only"
  ON public.events FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Enable delete for authenticated users only"
  ON public.events FOR DELETE TO authenticated USING (true);

-- group_mentoring_events
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.group_mentoring_events;
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.group_mentoring_events;
DROP POLICY IF EXISTS "Enable update for authenticated users only" ON public.group_mentoring_events;
DROP POLICY IF EXISTS "Enable delete for authenticated users only" ON public.group_mentoring_events;
CREATE POLICY "Enable insert for authenticated users only"
  ON public.group_mentoring_events FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable read access for authenticated users"
  ON public.group_mentoring_events FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable update for authenticated users only"
  ON public.group_mentoring_events FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Enable delete for authenticated users only"
  ON public.group_mentoring_events FOR DELETE TO authenticated USING (true);

-- mentors
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.mentors;
DROP POLICY IF EXISTS "Enable update access for authenticated" ON public.mentors;
DROP POLICY IF EXISTS "Enable insert for own mentor row" ON public.mentors;
DROP POLICY IF EXISTS "Enable delete for own mentor row" ON public.mentors;
CREATE POLICY "Enable read access for authenticated users"
  ON public.mentors FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable insert for own mentor row"
  ON public.mentors FOR INSERT TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "Enable update access for authenticated"
  ON public.mentors FOR UPDATE TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "Enable delete for own mentor row"
  ON public.mentors FOR DELETE TO authenticated
  USING ((SELECT auth.uid()) = user_id);

-- opportunities
DROP POLICY IF EXISTS "Enable delete for students based on user_id" ON public.opportunities;
DROP POLICY IF EXISTS "Enable delete for teachers based on email" ON public.opportunities;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON public.opportunities;
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.opportunities;
DROP POLICY IF EXISTS "Enable update for teachers based on email" ON public.opportunities;
DROP POLICY IF EXISTS "Enable upddate for users based on submitted_by" ON public.opportunities;
CREATE POLICY "Enable delete for students based on user_id"
  ON public.opportunities FOR DELETE TO authenticated
  USING ((SELECT auth.uid()) = submitted_by);
CREATE POLICY "Enable delete for teachers based on email"
  ON public.opportunities FOR DELETE TO authenticated
  USING (((SELECT auth.jwt()) ->> 'email') = review_teacher);
CREATE POLICY "Enable insert for authenticated users only"
  ON public.opportunities FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Enable read access for authenticated users"
  ON public.opportunities FOR SELECT TO authenticated USING (true);
CREATE POLICY "Enable update for teachers based on email"
  ON public.opportunities FOR UPDATE TO authenticated
  USING (((SELECT auth.jwt()) ->> 'email') = review_teacher)
  WITH CHECK (((SELECT auth.jwt()) ->> 'email') = review_teacher);
CREATE POLICY "Enable upddate for users based on submitted_by"
  ON public.opportunities FOR UPDATE
  USING ((SELECT auth.uid()) = submitted_by);

-- portfolios
DROP POLICY IF EXISTS "Enable insert for users based on user_id" ON public.portfolios;
DROP POLICY IF EXISTS "Enable select for users based on user_id" ON public.portfolios;
DROP POLICY IF EXISTS "Enable update for users based on user_id" ON public.portfolios;
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON public.portfolios;
CREATE POLICY "Enable insert for users based on user_id"
  ON public.portfolios FOR INSERT
  WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "Enable select for users based on user_id"
  ON public.portfolios FOR SELECT
  USING ((SELECT auth.uid()) = user_id);
CREATE POLICY "Enable update for users based on user_id"
  ON public.portfolios FOR UPDATE
  USING ((SELECT auth.uid()) = user_id);
CREATE POLICY "Enable delete for users based on user_id"
  ON public.portfolios FOR DELETE
  USING ((SELECT auth.uid()) = user_id);

-- profiles
DROP POLICY IF EXISTS "Enable insert for users based on user_id" ON public.profiles;
DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.profiles;
DROP POLICY IF EXISTS "update_own_profile" ON public.profiles;
CREATE POLICY "Enable insert for users based on user_id"
  ON public.profiles FOR INSERT
  WITH CHECK ((SELECT auth.uid()) = id);
CREATE POLICY "Enable read access for authenticated users"
  ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "update_own_profile"
  ON public.profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- profile_tokens: own-row only (no broad SELECT)
DROP POLICY IF EXISTS "profile_tokens_select_own" ON public.profile_tokens;
DROP POLICY IF EXISTS "profile_tokens_insert_own" ON public.profile_tokens;
DROP POLICY IF EXISTS "profile_tokens_update_own" ON public.profile_tokens;
DROP POLICY IF EXISTS "profile_tokens_delete_own" ON public.profile_tokens;
CREATE POLICY "profile_tokens_select_own"
  ON public.profile_tokens FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = id);
CREATE POLICY "profile_tokens_insert_own"
  ON public.profile_tokens FOR INSERT TO authenticated
  WITH CHECK ((SELECT auth.uid()) = id);
CREATE POLICY "profile_tokens_update_own"
  ON public.profile_tokens FOR UPDATE TO authenticated
  USING ((SELECT auth.uid()) = id)
  WITH CHECK ((SELECT auth.uid()) = id);
CREATE POLICY "profile_tokens_delete_own"
  ON public.profile_tokens FOR DELETE TO authenticated
  USING ((SELECT auth.uid()) = id);

-- user_events
DROP POLICY IF EXISTS "Enable delete for users based on user_id" ON public.user_events;
DROP POLICY IF EXISTS "Enable insert for users based on user_id" ON public.user_events;
DROP POLICY IF EXISTS "Enable read for users based on user_id" ON public.user_events;
CREATE POLICY "Enable delete for users based on user_id"
  ON public.user_events FOR DELETE
  USING ((SELECT auth.uid()) = user_id);
CREATE POLICY "Enable insert for users based on user_id"
  ON public.user_events FOR INSERT
  WITH CHECK ((SELECT auth.uid()) = user_id);
CREATE POLICY "Enable read for users based on user_id"
  ON public.user_events FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);


-- -------------------------------------------------------
-- Storage buckets + policies
-- -------------------------------------------------------

INSERT INTO storage.buckets (id, name, public)
VALUES
  ('portfolio',     'portfolio',     true),
  ('events',        'events',        true),
  ('opportunities', 'opportunities', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Give users access to own folder ijvnt4_0" ON storage.objects;
DROP POLICY IF EXISTS "Give users access to own folder ijvnt4_1" ON storage.objects;
DROP POLICY IF EXISTS "portfolio insert own folder" ON storage.objects;
DROP POLICY IF EXISTS "portfolio update own folder" ON storage.objects;
DROP POLICY IF EXISTS "portfolio select" ON storage.objects;
DROP POLICY IF EXISTS "Public read for opportunities bucket" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated insert for opportunities bucket" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated update for opportunities bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public read for events bucket" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated insert for events bucket" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated update for events bucket" ON storage.objects;
DROP POLICY IF EXISTS "Public read for portfolio bucket" ON storage.objects;

CREATE POLICY "portfolio insert own folder"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'portfolio'
    AND (SELECT auth.uid()::text) = (storage.foldername(name))[1]
  );

CREATE POLICY "portfolio update own folder"
  ON storage.objects FOR UPDATE TO authenticated
  USING (
    bucket_id = 'portfolio'
    AND (SELECT auth.uid()::text) = (storage.foldername(name))[1]
  );

CREATE POLICY "Public read for portfolio bucket"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'portfolio');

CREATE POLICY "Public read for opportunities bucket"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'opportunities');

CREATE POLICY "Authenticated insert for opportunities bucket"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'opportunities');

CREATE POLICY "Authenticated update for opportunities bucket"
  ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'opportunities');

CREATE POLICY "Public read for events bucket"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'events');

CREATE POLICY "Authenticated insert for events bucket"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'events');

CREATE POLICY "Authenticated update for events bucket"
  ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'events');


-- -------------------------------------------------------
-- Demo catalogue seed (16 opportunities + 4 events)
-- Images: public/img/seed/* served by Next.js (no Storage upload)
-- Contact emails are fictional @example.school placeholders
-- -------------------------------------------------------

DELETE FROM public.user_events WHERE event_id BETWEEN 9001 AND 9004;
DELETE FROM public.events WHERE event_id BETWEEN 9001 AND 9004;
DELETE FROM public.opportunities
WHERE opportunity_id IN (
  'a1000001-0000-4000-8000-000000000001',
  'a1000001-0000-4000-8000-000000000002',
  'a1000001-0000-4000-8000-000000000003',
  'a1000001-0000-4000-8000-000000000004',
  'a1000001-0000-4000-8000-000000000005',
  'a1000001-0000-4000-8000-000000000006',
  'a1000001-0000-4000-8000-000000000007',
  'a1000001-0000-4000-8000-000000000008',
  'a1000001-0000-4000-8000-000000000009',
  'a1000001-0000-4000-8000-000000000010',
  'a1000001-0000-4000-8000-000000000011',
  'a1000001-0000-4000-8000-000000000012',
  'a1000001-0000-4000-8000-000000000013',
  'a1000001-0000-4000-8000-000000000014',
  'a1000001-0000-4000-8000-000000000015',
  'a1000001-0000-4000-8000-000000000016'
);

INSERT INTO public.opportunities (
  opportunity_id, created_at, last_updated, title, full_description, url,
  submission_date, contact_name, contact_email, opportunity_type,
  internal, online, time_required, advice, weightage, cost, image,
  one_off, short_description, year_groups, subjects, custom_opportunity,
  status, review_teacher, submitted_by, review_text, past_projects
) VALUES
(
  'a1000001-0000-4000-8000-000000000001',
  now(), now(),
  'UKMT Senior Mathematical Challenge',
  'The UK Mathematics Trust Senior Mathematical Challenge is a 90-minute multiple-choice paper for students in Year 13 or below. It emphasises mathematical reasoning, precision, and fluency with core techniques on unfamiliar problems. Strong performances can lead to follow-on rounds including the Senior Kangaroo and British Mathematical Olympiad.',
  'https://www.ukmt.org.uk/competitions/solo/senior-mathematical-challenge',
  '2026-11-05',
  'Mathematics Coordinator', 'maths@example.school',
  'Competition', true, false, 1,
  'Work through recent past papers under timed conditions. Focus on strategy and careful reading rather than rushing every question.',
  4, 5, '/img/seed/ukmt.png', true,
  'A prestigious 90-minute maths competition testing problem-solving for senior students.',
  ARRAY[12,13]::numeric[], ARRAY['Mathematics','Further Mathematics']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000002',
  now(), now(),
  'UKMT Intermediate Mathematical Challenge',
  'Aimed at students in Years 9–11, the Intermediate Mathematical Challenge develops problem-solving habits early. The paper rewards ingenuity with school-level mathematics and is an excellent stepping stone toward Senior Challenge and Olympiad pathways.',
  'https://www.ukmt.org.uk/competitions/solo/intermediate-mathematical-challenge',
  '2027-02-04',
  'Mathematics Coordinator', 'maths@example.school',
  'Competition', true, false, 1,
  'Practise without a calculator. Review number, algebra, and geometry fundamentals, then attempt full papers in one sitting.',
  3, 5, '/img/seed/ukmt.png', true,
  'UKMT challenge for Years 9–11 building confidence with non-routine maths problems.',
  ARRAY[9,10,11]::numeric[], ARRAY['Mathematics']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000003',
  now(), now(),
  'British Physics Olympiad — Senior Physics Challenge',
  'Organised by the British Physics Olympiad, the Senior Physics Challenge asks students to apply A-level ideas to harder contexts. It is a recognised enrichment route for aspiring physicists and often sits alongside school physics mentoring.',
  'https://www.bpho.org.uk/bpho/as-challenge.html',
  '2027-01-30',
  'Physics Coordinator', 'physics@example.school',
  'Competition', true, false, 1,
  'Complete at least four past papers. Revisit mechanics, waves, and electricity, and practise explaining multi-step reasoning clearly.',
  4, 0, '/img/seed/bpho.png', true,
  'A respected physics challenge extending Year 12–13 syllabus ideas into Olympiad-style problems.',
  ARRAY[12,13]::numeric[], ARRAY['Physics','Mathematics']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000004',
  now(), now(),
  'UK Chemistry Olympiad',
  'The Royal Society of Chemistry''s UK Chemistry Olympiad stretches secondary students beyond the A-level syllabus. Round 1 is a written paper taken in school; high scorers may progress toward national training and international selection.',
  'https://edu.rsc.org/enrichment/uk-chemistry-olympiad',
  '2027-01-23',
  'Chemistry Coordinator', 'chemistry@example.school',
  'Competition', true, false, 1,
  'Review topics slightly beyond A-level, especially organic mechanisms and physical chemistry calculations. Past papers are essential.',
  5, 0, '/img/seed/rsc.png', true,
  'RSC chemistry competition pushing students into creative problem-solving beyond A-level.',
  ARRAY[11,12,13]::numeric[], ARRAY['Chemistry']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000005',
  now(), now(),
  'British Biology Olympiad',
  'The British Biology Olympiad challenges students with data interpretation, experimental design, and advanced biology content. It is ideal for Year 12–13 biologists aiming for competitive university applications.',
  'https://www.ukbiologycompetitions.org/british-biology-olympiad/',
  '2027-02-12',
  'Biology Coordinator', 'biology@example.school',
  'Competition', true, false, 1,
  'Read widely beyond the specification—Nature summaries and past Olympiad papers help. Practise extracting conclusions from graphs and tables.',
  5, 0, '/img/seed/biology.png', true,
  'National biology competition combining syllabus depth with data and experimental reasoning.',
  ARRAY[12,13]::numeric[], ARRAY['Biology','Chemistry']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000006',
  now(), now(),
  'Bebras Computing Challenge',
  'Bebras is an international computational-thinking contest suitable from Year 7 upwards. Tasks emphasise logic, algorithms, and pattern recognition without requiring prior programming experience—making it an excellent entry point into computer science enrichment.',
  'https://www.bebras.uk/',
  '2026-11-10',
  'Computer Science Coordinator', 'computing@example.school',
  'Competition', true, true, 1,
  'Try sample tasks online and discuss strategies with classmates. Programming helps but is not required.',
  3, 0, '/img/seed/bebras.png', true,
  'International computational-thinking contest open across year groups—no coding required.',
  ARRAY[7,8,9,10,11,12,13]::numeric[], ARRAY['Computer Science','Mathematics']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000007',
  now(), now(),
  'Oxford University Computing Challenge',
  'A follow-on style contest linked with Bebras pathways, the Oxford University Computing Challenge deepens computational problem-solving for students who enjoy algorithmic puzzles and want a university-branded enrichment signal.',
  'https://www.bebras.uk/index.php?action=user_competitions',
  '2027-03-05',
  'Computer Science Coordinator', 'computing@example.school',
  'Competition', true, true, 1,
  'Complete Bebras first where possible. Practise breaking problems into steps and checking edge cases carefully.',
  4, 0, '/img/seed/oxford.png', true,
  'University-linked computing challenge building on computational thinking skills.',
  ARRAY[10,11,12,13]::numeric[], ARRAY['Computer Science','Mathematics']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000008',
  now(), now(),
  'Young Economist of the Year',
  'Run with the Royal Economic Society and the Financial Times, this essay competition asks students to analyse a live economic question with clarity and evidence. It is highly valued by economics applicants.',
  'https://www.res.org.uk/education/young-economist-of-the-year.html',
  '2027-06-30',
  'Economics Coordinator', 'economics@example.school',
  'Competition', false, true, 3,
  'Read the FT and Economist regularly. Plan a clear thesis, use data carefully, and leave time to edit for style.',
  5, 0, '/img/seed/res.png', true,
  'RES / FT essay competition applying economic theory to a current global issue.',
  ARRAY[12,13]::numeric[], ARRAY['Economics']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000009',
  now(), now(),
  'Young Geographer of the Year',
  'The Royal Geographical Society with IBG invites students to investigate a geographical theme and present findings creatively. Entries can combine fieldwork, GIS, cartography, and extended writing.',
  'https://www.rgs.org/schools/competitions/young-geographer-of-the-year/',
  '2026-10-16',
  'Geography Coordinator', 'geography@example.school',
  'Competition', false, true, 3,
  'Pick a question you care about. Mix primary and secondary evidence, and present maps or diagrams with clear captions.',
  4, 0, '/img/seed/rgs.png', true,
  'RGS competition showcasing geographical enquiry, creativity, and communication.',
  ARRAY[10,11,12,13]::numeric[], ARRAY['Geography']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000010',
  now(), now(),
  'Nuffield Research Placements',
  'Nuffield Research Placements give post-16 STEM students the chance to work alongside professional scientists, engineers, and mathematicians on a real research project—typically over the summer—with mentoring and a final report or presentation.',
  'https://www.nuffieldfoundation.org/students-teachers/nuffield-research-placements',
  '2027-03-15',
  'STEM Enrichment Lead', 'stem@example.school',
  'Project', false, false, 4,
  'Apply early. Show curiosity about a research area and readiness to learn lab or coding skills on the job.',
  5, 0, '/img/seed/nuffield.png', true,
  'Summer research placements with professional STEM mentors for Year 12 students.',
  ARRAY[12]::numeric[], ARRAY['Biology','Chemistry','Physics','Computer Science','Mathematics','Engineering']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000011',
  now(), now(),
  'Young Enterprise Company Programme',
  'Students form a real company for the school year: elect a board, raise share capital, design a product or service, and manage marketing, finance, and operations. It is one of the strongest entrepreneurship experiences available in UK schools.',
  'https://www.young-enterprise.org.uk/programmes/company-programme/',
  '2027-05-31',
  'Business Coordinator', 'business@example.school',
  'Project', true, false, 5,
  'Treat it like a real startup—document decisions, listen to customers, and be ready to pivot. Keep clear financial records.',
  5, 50, '/img/seed/young-enterprise.png', false,
  'Year-long programme running a student company with real products, finance, and marketing.',
  ARRAY[11,12,13]::numeric[], ARRAY['Business','Economics']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000012',
  now(), now(),
  'Model United Nations (THIMUN-style)',
  'Students represent countries in simulated UN committees, drafting resolutions and negotiating under formal procedure. MUN builds research, public speaking, and diplomacy skills prized by politics, law, and IR applicants.',
  'https://www.thimun.org/',
  '2027-01-25',
  'Politics Coordinator', 'politics@example.school',
  'Competition', false, false, 2,
  'Research your assigned country thoroughly, learn UN procedure, and practise short, persuasive speeches.',
  4, 100, '/img/seed/thimun.png', true,
  'Simulate UN debate—research, negotiate, and draft resolutions on global issues.',
  ARRAY[10,11,12,13]::numeric[], ARRAY['Politics','History','Economics','English Language']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000013',
  now(), now(),
  'European Youth Parliament',
  'EYP brings young people together to debate current European and global issues in a parliamentary format. Participants develop intercultural awareness, teamwork, and structured argumentation.',
  'https://eyp.org/',
  '2026-09-20',
  'Politics Coordinator', 'politics@example.school',
  'Competition', false, false, 2,
  'Follow European current affairs and practise debating with evidence rather than opinion alone.',
  4, 150, '/img/seed/eyp.png', true,
  'International parliamentary simulation developing debate and intercultural skills.',
  ARRAY[11,12,13]::numeric[], ARRAY['Politics','Economics','History','French','Spanish']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000014',
  now(), now(),
  'Forage — PwC Power BI Job Simulation',
  'A free virtual work experience on Forage where students complete short tasks inspired by real PwC data analytics work, including Power BI visualisation. Useful for economics, business, and computer science students exploring consulting careers.',
  'https://www.theforage.com/simulations/pwc-ch/power-bi-cqxg',
  NULL,
  'Careers Coordinator', 'careers@example.school',
  'Course', false, true, 2,
  'Block out focused sessions. If Power BI is new, budget extra time and keep notes for your portfolio reflection.',
  3, 0, '/img/seed/forage.png', true,
  'Free virtual work experience building Power BI and data storytelling skills with a PwC-branded pathway.',
  ARRAY[10,11,12,13]::numeric[], ARRAY['Computer Science','Economics','Business','Mathematics']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000015',
  now(), now(),
  'Young Artists'' Summer Show',
  'An open-submission exhibition for young artists organised with the Royal Academy of Arts. Selected work may be shown online and on-site—an outstanding opportunity for Art & Design portfolios.',
  'https://youngartists.royalacademy.org.uk/',
  '2027-04-27',
  'Art Coordinator', 'art@example.school',
  'Competition', false, false, 3,
  'Select your strongest piece, photograph it well, and write a concise artist statement that explains intent and process.',
  4, 0, '/img/seed/royal-academy.png', true,
  'Submit artwork for a prestigious Royal Academy-linked youth exhibition.',
  ARRAY[10,11,12,13]::numeric[], ARRAY['Art & Design','Photography','Graphic Communications']::text[],
  false, 'active', NULL, NULL, NULL, NULL
),
(
  'a1000001-0000-4000-8000-000000000016',
  now(), now(),
  'UK Linguistics Olympiad',
  'The UK Linguistics Olympiad presents language puzzles that reward pattern recognition and logical deduction—no prior linguistics study required. Excellent enrichment for languages students and anyone curious about how language works.',
  'https://www.uklo.org/',
  '2027-02-04',
  'Languages Coordinator', 'languages@example.school',
  'Competition', false, true, 1,
  'Attempt past rounds for fun. Focus on spotting systematic patterns rather than translating word-by-word.',
  4, 0, '/img/seed/linguistics.png', true,
  'National linguistics puzzle contest—ideal for language lovers and analytical thinkers.',
  ARRAY[9,10,11,12,13]::numeric[], ARRAY['French','Spanish','Arabic','English Language','English Literature']::text[],
  false, 'active', NULL, NULL, NULL, NULL
);

INSERT INTO public.events (
  event_id, created_at, title, category, date, start_time, end_time, poster,
  description, contact_name, contact_email, sub_category, year_groups,
  google_event_id, invite_link
) VALUES
(
  9001, now(),
  'Imperial College London — Engineering Insight Talk',
  'Talk',
  '2026-10-08',
  '14:45:00+04', '15:45:00+04',
  '/img/seed/imperial.png',
  'Admissions tutors and current students from Imperial College London discuss engineering pathways, course structure, and how to strengthen applications through supercurricular exploration.',
  'Careers Coordinator', 'careers@example.school',
  'University', ARRAY[11,12,13]::numeric[],
  NULL, NULL
),
(
  9002, now(),
  'Cambridge Admissions — STEM Subject Masterclass',
  'Talk',
  '2026-11-19',
  '16:00:00+04', '17:15:00+04',
  '/img/seed/cambridge.png',
  'A subject masterclass style session covering how Cambridge looks at academic exploration beyond the classroom, with tips on reading, problem-solving, and interview preparation for STEM applicants.',
  'Higher Education Lead', 'he@example.school',
  'University', ARRAY[12,13]::numeric[],
  NULL, NULL
),
(
  9003, now(),
  'Sixth Form Careers Fair',
  'External Event',
  '2027-01-14',
  '12:10:00+04', '13:40:00+04',
  '/img/seed/forage.png',
  'Meet employers, apprenticeship providers, and university outreach teams. Bring questions about work experience, degree apprenticeships, and sector pathways across STEM, business, and the creative industries.',
  'Careers Coordinator', 'careers@example.school',
  'Careers', ARRAY[10,11,12,13]::numeric[],
  NULL, NULL
),
(
  9004, now(),
  'Institute of Physics — Women in Physics Evening',
  'Talk',
  '2027-03-05',
  '17:30:00+04', '18:45:00+04',
  '/img/seed/iop.png',
  'An evening talk hosted with the Institute of Physics community, featuring physicists discussing research careers, university options, and how to get involved in competitions such as the British Physics Olympiad.',
  'Physics Coordinator', 'physics@example.school',
  'STEM', ARRAY[10,11,12,13]::numeric[],
  NULL, NULL
)
ON CONFLICT (event_id) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  date = EXCLUDED.date,
  start_time = EXCLUDED.start_time,
  end_time = EXCLUDED.end_time,
  poster = EXCLUDED.poster,
  description = EXCLUDED.description,
  contact_name = EXCLUDED.contact_name,
  contact_email = EXCLUDED.contact_email,
  sub_category = EXCLUDED.sub_category,
  year_groups = EXCLUDED.year_groups;

SELECT setval(
  'public.events_event_id_seq',
  GREATEST((SELECT COALESCE(MAX(event_id), 1) FROM public.events), 9004)
);
